### ISSUE TITLE
QuestionSubmitted is failing tests

### ISSUE THREAD

**Issue by jlowe64** [LearningLocker/Moodle-xAPI-Translator#33]
@garemoko QuestionsSubmitted is having issues. The basics are, I believe in the https://github.com/LearningLocker/Moodle-Log-Expander repo, the information from the test regarding questions is totally wrong. It simply repeats the test attempt information in the question area, and only tests if that information is present and in the correct number. However, when that information is being passed back to this repo, QuestionSubmitted.php needs to have certain fields in order to build the Translator Event, but it instead gets the following array repeated for every question:

```
(
    [id] => 1
    [username] => test_username
    [lang] => en
    [fullname] => test_fullname
    [summary] => test_summary
    [name] => test_name
    [intro] => test_intro
    [timestart] => 1433946701
    [timefinish] => 1433946702
    [state] => finished
    [course] => 1
    [sumgrades] => 1
    [grade] => 2
    [quiz] => 1
    [assignment] => 1
    [userid] => 1
    [forum] => 1
    [type] => object
    [scorm] => 1
    [grademax] => 5.00000
    [grademin] => 0.00000
    [gradepass] => 5.00000
    [commenttext] => <p>test comment</p>
    [questionid] => 1
)
```

Because this doesn't hold the relevant keys, `question->questiontext`, being one of them, it fails the test.

**Comment by garemoko** [comment]
@jlowe64 thanks for testing this for me. I need to get a handle on how the integration tests work and might need to have a chat at some point. Are you at Learning Technologies next week by any chance? 

Let's proceed on Github for now though. How do the integration tests actually work, is it the case that the data gets pulled from https://github.com/LearningLocker/Moodle-Log-Expander/blob/master/tests/TestRepository.php#L12 and then passed through the whole chain? If so, I can see that I need to considerably beef up the fields included (and I may as well test those fields at the same time).

**Comment by jlowe64** [comment]
@garemoko don't worry, I sometimes find it very difficult to debug this system. Although, it does make it much simpler to create the tests alongside each revision of a verb addition so it's easier to know where/when things fail. 

I haven't been invited to LT next week. I think my manager was planning on being there and chatting with Ben Betts, but he's not asked me to attend. I suspect if he does want me there it'll be last minute. 

Yes, when I run the tests located at https://github.com/jlowe64/moodle-logstore_xapi/tree/master/tests it passes through each library, passing along information as it goes through all three libraries. Whatever happens in Expander, goes to Translator, and then to Emitter. So from end to end, we know that an event is getting its true information in the end. 

I did see some tests/variables lacking in Expander, which I believe is causing this fail. Looking at the code itself, it does seem that it would work if the tests were adjusted. I didn't see anything glaring.

**Comment by garemoko** [comment]
@jlowe64 Thanks. That gives me a clear direction.

**Comment by ryansmith94** [comment]
I should note that those tests do not use the test data in the Expander. Those tests have their own separate test data (I can't remember why that is). See the [base TestCase](https://github.com/jlowe64/moodle-logstore_xapi/blob/master/tests/TestCase.php#L56) for example.

**Comment by ryansmith94** [comment]
Ah the test data is separate because the controllers are also tested (rather than just the events). From what I can see the the integration tests just check that the statement is valid at the end.

**Comment by jlowe64** [comment]
@ryansmith94 ahh, I did not see that. I assumed because of the data I was getting. Sorry about that. Thanks for clearing it up.

**Comment by ryansmith94** [comment]
No worries

**Comment by garemoko** [comment]
@ryansmith94 thanks! That saved me going off in the wrong direction. Just about to look at this now.

**Comment by garemoko** [comment]
OK, so looking at https://github.com/jlowe64/moodle-logstore_xapi/blob/master/tests/TestCase.php#L29-L42 it seems like the integrations tests are going to need similar overhaul to what we've given process_events in terms of handling arrays of events instead of events and allowing for the translator to output multiple events and types of events from a single input event. 

I suspect that @micaherne will have done some or all of this work in addressing https://github.com/jlowe64/moodle-logstore_xapi/issues/43 so for that reason I'm going to hold off looking at that aspect this until his work merges. We can actually probably get the tests passing without that work, but I imagine they would be missing the question level statements. 

What i can do for now is look at adding the missing properties for AttemptReviewedTest. Digging into the code more, I think that @jlowe64 might be right that the data that would come from Moodle's database is in fact coming from the test repository. The TestCase.php constructInput only contains data that would be included in the event. So, I'm going to revert back to @jlowe64's original suggestion and ignore @ryansmith94 in this case! Please tell me if (and how) I'm wrong.

**Comment by jlowe64** [comment]
@garemoko I'm on this tomorrow.

**Comment by jlowe64** [comment]
This is now passing.
